default:
  image: node:20

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"

stages:
  - install
  - build
  - test
  - release

include:
  - local: '.gitlab/ci/install.yml'
  - local: '.gitlab/ci/build.yml'
  - local: '.gitlab/ci/test.yml'
  - local: '.gitlab/ci/publish.yml'
