import { ReferenceLink } from "../../../model/types";

export interface IATFTestResultItem {
    get performanceRun(): ReferenceLink;
    set performanceRun(value: ReferenceLink);
    get runTimeMillis(): number;
    set runTimeMillis(value: number);
   
    get sysId(): string;
    set sysId(value: string);
    get sysUpdatedBy(): string;
    set sysUpdatedBy(value: string);
    get sysUpdatedOn(): Date;
    set sysUpdatedOn(value: Date);
    get sysCreatedBy(): string;
    set sysCreatedBy(value: string);
    get sysCreatedOn(): Date;
    set sysCreatedOn(value: Date);
    get sysModCount(): number;
    set sysModCount(value: number);
    get testResult(): ReferenceLink;
    set testResult(value: ReferenceLink);
    get description(): string;
    set description(value: string);
    get testCaseJson(): string;
    set testCaseJson(value: string);
    get output(): string;
    set output(value: string);
    get summary(): string;
    set summary(value: string);
    get type(): string;
    set type(value: string);
    get status(): string;
    set status(value: string);
    get startTime(): Date;
    set startTime(value: Date);
    get endTime(): Date;
    set endTime(value: Date);
    get runTime(): string;
    set runTime(value: string);
    get recordedAt(): number;
    set recordedAt(value: number);
    get step(): ReferenceLink;
    set step(value: ReferenceLink);
    get endTimeMillis(): string;
    set endTimeMillis(value: string);
    get whitelistedClientError(): ReferenceLink;
    set whitelistedClientError(value: ReferenceLink);
    get startTimeMillis(): string;
    set startTimeMillis(value: string);
}
